### ISSUE TITLE
dacBy default "-odac"

### ISSUE THREAD

**Issue by uliss** [anton-k/csound-expression#21]
`$ dacBy (mconcat [setDacBy "3"])  $ osc 440`

results in outputting to default device (1), because csound command line options have higher priority then in `<CsdOptions>`

**Comment by anton-k** [comment]
So I need to set `-odac` in the options not in the cmd line expression?

**Comment by uliss** [comment]
yes, I think so

**Comment by anton-k** [comment]
It's fixed in source. it's going to be the part of next release
