### ISSUE TITLE
how to specify number of input channels?

### ISSUE THREAD

**Issue by uliss** [anton-k/csound-expression#22]
As I understand, number of output channels `nchnls` is calculated automatically by Sig Tuple length.

Is it possible to specify `nchnls_i` value for number of input channels?

**Comment by anton-k** [comment]
I hear about this feature for the first time. How do you use it? Plain `in`, `ins` just works without `nchnls_i`.

**Comment by uliss** [comment]
for example, we have soundcard with 6 inputs and 6 outputs.
we try to output channel 5
`let ain = distortion (sig 1) $ inch [5] `
`dac $ ain`

and we get this error message from CSound: `Input channel 5 too large; ignored`
http://www.csounds.com/manual/html/nchnls_i.html

this happens by the reason: "The highest number for `kchan` available for use with inch depends on `nchnls_i`. If `kchan` is greater than `nchnls_i`, `ain` will be silent. Note that inch will give a warning but not an error in this case. "

described here: http://www.csounds.com/manual/html/inch.html

I found workaround:
`let ain = distortion (sig 1) $ inch [1]`
`let silence = upsamp 0`
`dac $ (ain, silence, silence, silence, silence, silence)`

this works, I think because output stream of six channels results in `nchnls = 6`. And by default, if `nchnls_i` not set, `nchnls` used. 
Thus problem exists when number of input channels greater than number of output channels.

**Comment by anton-k** [comment]
I see. Thanks for comments. It's fixed in source. it's going to be the part of next release

**Comment by anton-k** [comment]
In the next release user have to use an instance for functions for `nchnls_i` to be set.

There are instances 

~~~haskell
instance  Sigs a => RencderCsd (a -> SigN)
instance  Sigs a => RencderCsd (a -> SE SigN)
~~~

So the program that expects inputs is a function from inputs to outputs. 
Here is an example:

~~~haskell
module Try where

import Csound.Base

f :: Sig6 -> Sig2
f _ = pan2 asig k
	where 
		k = inch [1]
		asig = saw 110

main = dac f
~~~

**Comment by anton-k** [comment]
and we probably need to specify the custom input source with 

~~~haskell
setAdcBy :: String -> Options
~~~
