### ISSUE TITLE
coremidi support

### ISSUE THREAD

**Issue by uliss** [anton-k/csound-expression#23]
Please, add `CoreMidi` to `Rtmidi` constructors. It's strange, but in documentaion of csound there's no word about this driver on MacOSX. 
But here it is: http://en.flossmanuals.net/csound/c-configuring-midi

PS. Anton, thank you for your wonderfull software and quick fixes.

**Comment by anton-k** [comment]
Thanks for the kind words! It's fixed and it's on hackage with another updates. I'm happy to know that an accomplished musician like you finds my library useful. Please tell me if you manage to get a real live performance with it. It would be a great motivation for me to continue the work.

**Comment by anton-k** [comment]
I saw your video with a delay line. smth similar can be achieved with function `echo` with feedback set to maximum (ie 1). Here is the code with low pass filter, delay, reverb and looper. It reads from the input:

~~~haskell
ef :: Sig2 -> SE Sig2
ef a = at smallHall2 $ at (echo 4 1) $ at (echo 0.25 0.85) $ at (mlp 1500 0.1) $ a

main = run ef
~~~

**Comment by uliss** [comment]
Yes, I'm going to rewrite it from PureData to Csound-expression. 
There's some control required via MIDI or Osc. But the main principe is as you wrote.

Also, could you give some examples of using Osc?
Because in tutorial `::t initOsc :: OscPort -> OscRef`, but in current version is: `initOsc :: OscPort -> SE OscRef`
How we can trigger events from `listenOsc`? For example: how can we make fadein after recieving "/control/start" message? or how to play instrument after getting, say "/instr/1"?

**Comment by anton-k** [comment]
It's described here http://hackage.haskell.org/package/csound-expression-4.4.1/docs/Csound-Control-Osc.html

To receive/send messages we need to init the osc-channel. We do it with the function:

~~~haskell
ref <- initOsc n -- argument is an integer port number
~~~

We get the reference. Then we can listen for messages.

~~~haskell
listenOsc :: forall a. Tuple a => OscRef -> OscAddress -> OscType -> Evt a
~~~

Osc message is a string  and a value. We specify string with first arg and te type of value with the second one. We get back an event stream of values. there are many functions to process event streams, to convert them to signals or trigger instruments.

http://hackage.haskell.org/package/csound-expression-4.4.1/docs/Csound-Control-Evt.html
http://hackage.haskell.org/package/csound-expression-4.4.1/docs/Csound-Control-Instr.html

PS: I've never used OSC. I've just recoded the csound opcodes in idiomatic way. I should test it out.

Complete example to try out

~~~haskell
instr :: D -> SE Sig
instr _ = return $ osc 440

main = dac $ do
    ref <- initOsc 1234
    let evt = filterE  ( ==* 1) $ (listeOsc "instr" "i") :: Evt D
    return $ sched instr $ withDur 1 $ evt 
~~~

**Comment by anton-k** [comment]
With `filterE` we can filter th even streams. Here we get only stream with ones. 
The sched function triggers an instrument when smth happens on the event stream.
withDur attaches the fixed note length to the event value. 

~~~haskell
filterE :: (a -> BoolD) -> Evt a -> Evt a
withDur :: D -> Evt a -> Evt (D, a)
sched :: (Arg a, Sigs b) => (a -> SE b) -> Evt a -> b
~~~

**Comment by anton-k** [comment]
Docs on the original functions

http://www.csounds.com/manual/html/OSCNetwork.html
