### ISSUE TITLE
Csound.Air.Fx equalizer problem

### ISSUE THREAD

**Issue by uliss** [anton-k/csound-expression#24]
```haskell
let eq_levels = zip (iterate id 0.5) $ fmap (*100) [1,4,16,64]
dac $ equalizer eq_levels 1 $ saw 1000
```

results in this csound (csound-6.04) error:
```
INIT ERROR in instr 18: table: index type inconsistent with output
ar0	table.a	1.0	1	1.0	0	0	
	  B  0.000 - note deleted.  i18 had 1 init errors
```

it happens because the first argument for `table` should be the same as a return type.
http://www.csounds.com/manual/html/table.html

if we use:
```haskell
dac $ equalizer eq_levels (upsamp 1) $ saw 1000
```
csound error disappered, but there's another problem - no sound at all.

As I think, a something strange happens in `defineTabArgs` function of GEN16 routine:
```haskell
substGen16 durs xs = case (durs, xs) of 
            ([], as) -> as
            (_, [])  -> []
            (d:ds, valN:_:typeN:rest)   -> valN : d : (typeN * d) : substGen16 ds rest
            (_, _)   -> xs
```
Are you shure that 3rd argument should be multiplied by d: `(typeN * d)`?

http://www.csounds.com/manual/html/GEN16.html

**Comment by anton-k** [comment]
Yes, you are right. Actually three bugs are involved. 

* we can not use constants in place of a and k-rate signals in the arguments of opcodes 
   (sometimes we can sometimes we ca not) it's an odd behavior. In the new version constants are 
   substituted only for i-rate variables. So the line
   
   ~~~
   ares oscil 1, 440
   ~~~

   becomes

   ~~~
   kr1 = 1
   kr2 = 440
  ares oscil kr1, kr2 
   ~~~

* the last two bugs stem from the gen16. You are right with suspicious code.
   The last bug is with gen16 size rescaling. 

It's fixed. The code in the issue produces sound. Thanks for the report. 
I'm going to update soon (this weekend).
